## Numpy

### Numpy Básico

#### Importando biblioteca

In [1]:
import numpy as np

#### Criando array de 1 dimensão

In [5]:
one_dim = np.array([1,2,3,4])
one_dim

array([1, 2, 3, 4])

#### Quantidade de dimensões

In [6]:
one_dim.ndim

1

#### Criando array de 2 dimensões

In [8]:
two_dim = np.array([(1,2,3),(4,5,6)])
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

#### Criar array com números aleatórios

Array de 5 linhas e 2 dimensões

In [9]:
np.random.random((5,2))

array([[0.20798251, 0.98538158],
       [0.90839397, 0.38614722],
       [0.81275494, 0.19543528],
       [0.99174359, 0.88692654],
       [0.70128123, 0.60443651]])

#### Criar um array com valores esparsos esparsos iniciando com 10, menor que 50 e incrementando de 5 em 5

In [10]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

#### Criar um array linear de 0 a 2 de no máximo 9 elementos

In [16]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

#### Criar um array de zeros

In [19]:
# 3 rows x 4 columns
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Numpy Arrays vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida
- Listas não permitem operações em todos os elementos da lista. Para operações em todos os elementos é preciso iterar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos.
- Arrays Numpy consideram todos os elementos de tipos distintos como strings. 

#### Criando listas Python

In [20]:
lista = [1, 2, 3]

#### Multiplicar valores da lista por 2

In [21]:
lista * 2

[1, 2, 3, 1, 2, 3]

#### Transforme a variável lista em um array Numpy

In [22]:
lista = np.array(lista)

In [23]:
type(lista)

numpy.ndarray

#### Multiplicando cada item do array numpy

In [24]:
lista * 2

array([2, 4, 6])

#### Exemplo: Calcular IMC de pessoas

In [26]:
pesos = [67, 81, 120, 90]
altura = [1.68, 1.70, 1.75, 1.85]

**Tentando calcular com listas**

In [27]:
pesos / altura ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**Calculando com Numpy**

In [28]:
pesos = np.array(pesos)
altura = np.array(altura)

In [29]:
pesos / altura ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

#### Arrays Numpy armazenam elementos com String quando existe algum elemento não inteiro ou não float

In [30]:
a = np.array([1, 3, 'Casa', True])

In [31]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

**Calculo dá erro, pois não são do tipo inteiro ou float**

In [32]:
a * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

### Métodos e Atributos Úteis

#### No Jupyter notebook, digite o '.' e pressione o 'tab' para visualizar os métodos disponíveis

In [35]:
two_dim.

SyntaxError: invalid syntax (<ipython-input-35-8831a6ec781d>, line 1)

#### shape: tamanho no formato linhas x colunas

In [36]:
two_dim.shape

(2, 3)

#### ndim: retorna a quantidade de dimensões

In [37]:
two_dim.ndim

2

#### max: retorna o valor máximo do array

In [39]:
two_dim.max()

6

#### min: retorna o valor mínimo do array

In [40]:
two_dim.min()

1

#### mean: retorna o valor médio do array

In [41]:
two_dim.mean()

3.5

#### std: retorna o desvio padrão do array

In [42]:
two_dim.std()

1.707825127659933

#### dtype: retorna o tipo de dados do array

In [45]:
two_dim.dtype

dtype('int64')

#### size: retorna a quantidade de elementos dentro do array

In [46]:
two_dim.size

6

#### itemsize: mostra a quantidade em bytes dos elementos

In [47]:
two_dim.itemsize

8

#### sum: retorna a soma de todos elementos do array

In [48]:
two_dim.sum()

21

### Transformando Arrays

#### Transposta da Matriz - nparray.T

In [49]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Transformar uma matriz em um array

**Uso muito comum em bibliotecas de Machine Learning**

In [61]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

#### Transformando uma matriz 5 x 3 em uma matriz 3 x 5

In [58]:
tree = np.random.random((5, 3))
tree

array([[0.5968339 , 0.25948805, 0.26160492],
       [0.38802309, 0.04291735, 0.53646541],
       [0.35261558, 0.75891689, 0.36508932],
       [0.33186647, 0.16843952, 0.15122813],
       [0.66158876, 0.62866738, 0.78553935]])

In [59]:
tree.shape

(5, 3)

In [60]:
tree.reshape(3,5)

array([[0.5968339 , 0.25948805, 0.26160492, 0.38802309, 0.04291735],
       [0.53646541, 0.35261558, 0.75891689, 0.36508932, 0.33186647],
       [0.16843952, 0.15122813, 0.66158876, 0.62866738, 0.78553935]])

#### Adicionando elementos em um Array

In [81]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [84]:
# np.insert(array, index, values)
two_dim = np.insert(two_dim, 0, [10])
two_dim

array([10,  1,  2,  3,  4,  5,  6])

#### Excluindo elemento

In [85]:
two_dim = np.delete(two_dim, [0])
two_dim

array([1, 2, 3, 4, 5, 6])

#### Salvando array em arquivo .txt

In [89]:
np.savetxt("./output/dataset_array_numpy", two_dim, delimiter=',')

### Acessando dados do Array

#### Criando array exemplo

In [91]:
my_array = np.random.random([10, 2])
my_array

array([[0.21944452, 0.20100918],
       [0.72634442, 0.31996775],
       [0.86399952, 0.66278192],
       [0.48091599, 0.81609481],
       [0.7560191 , 0.9898297 ],
       [0.96027888, 0.18387974],
       [0.32531389, 0.37704739],
       [0.12890967, 0.65468573],
       [0.12550194, 0.22608206],
       [0.89536819, 0.35210221]])

#### Lendo elementos do array

##### Lendo a primeira linha

In [92]:
my_array[0]

array([0.21944452, 0.20100918])

##### Lendo o primeiro elemento da coluna 0

In [93]:
my_array[0][0]

0.21944452284741056

##### Lendo o primeiro elemento da coluna 1

In [94]:
my_array[0][1]

0.20100917704740917

##### Lendo o segundo elemento da coluna 1 

In [98]:
my_array[1][1]

0.3199677534658567

##### Lendo o segundo elemento da coluna 1 

In [97]:
my_array[1,1]

0.3199677534658567

#### Lendo usando slice

##### Lendo 3 primeiros elementos da coluna 1

In [96]:
my_array[:3, 1]

array([0.20100918, 0.31996775, 0.66278192])

##### Lendo todas as linhas da coluna 1

In [99]:
my_array[:, 1]

array([0.20100918, 0.31996775, 0.66278192, 0.81609481, 0.9898297 ,
       0.18387974, 0.37704739, 0.65468573, 0.22608206, 0.35210221])

##### Lendo todos os elementos da coluna 1 e multiplicando por 10

In [100]:
my_array[:, 1] * 10

array([2.01009177, 3.19967753, 6.62781916, 8.16094813, 9.89829698,
       1.83879744, 3.77047393, 6.54685728, 2.26082059, 3.52102213])

#### Lendo usando condição com arrays

In [101]:
my_array > 0.50

array([[False, False],
       [ True, False],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False]])

In [102]:
my_array[my_array > 0.50]

array([0.72634442, 0.86399952, 0.66278192, 0.81609481, 0.7560191 ,
       0.9898297 , 0.96027888, 0.65468573, 0.89536819])

### Carregando Arrays Numpy a partir de arquivos de Texto

#### Lendo array 1 dim

In [106]:
dataset = np.loadtxt("./output/dataset_array_numpy", delimiter=',')
dataset

array([1., 2., 3., 4., 5., 6.])

In [104]:
dataset.shape

(6,)

#### Lendo multiplas colunas dividindo em arrays

In [107]:
a, b, c = np.loadtxt("./dados/dataset_valores.txt", skiprows=1, unpack=True)

In [108]:
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [109]:
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [110]:
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

#### Lendo arquivo preenchendo valores não numéricos com zero

In [112]:
dataset = np.genfromtxt("./dados/dataset_valores_vazio.txt", skip_header=2, filling_values=0)

In [113]:
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])